'use strict';
const http=require('node:http'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {generate,wall}=require('./shared');
const PORT=Number(process.env.PORT||3000), ROOT=path.resolve(__dirname,'public');
const rooms=new Map(),clients=new Set();
const riddles={sigil1:{question:'ما الشيء الذي كلما أخذت منه كبر؟',choices:['الظل','الحفرة','المفتاح'],answer:1},sigil2:{question:'له أسنان كثيرة لكنه لا يعض، ما هو؟',choices:['المشط','الذئب','القفل'],answer:0},sigil3:{question:'٢ ، ٤ ، ٨ ، ١٦ ... ما الرقم التالي لفتح القفل؟',choices:['٢٤','٣٠','٣٢'],answer:2}};
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{
  if((req.url||'').split('?')[0]==='/shared.js'){res.writeHead(200,{'Content-Type':'application/javascript; charset=utf-8'});return fs.createReadStream(path.join(__dirname,'shared.js')).pipe(res);}
  if(req.url==='/health'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify({ok:true,rooms:rooms.size}));}
  let name=decodeURIComponent((req.url||'/').split('?')[0]);if(name==='/')name='/index.html';
  const file=path.resolve(ROOT,'.'+name);if(!(file===ROOT||file.startsWith(ROOT+path.sep))){res.writeHead(403);return res.end();}
  const servePath=fs.existsSync(file)&&fs.statSync(file).isFile()?file:path.resolve(ROOT,'index.html');
  fs.readFile(servePath,(err,body)=>{if(err){res.writeHead(404);return res.end('Not found');}res.writeHead(200,{'Content-Type':mime[path.extname(servePath)]||'application/octet-stream','Cache-Control':servePath.endsWith('.html')?'no-cache':'public, max-age=1800','X-Content-Type-Options':'nosniff'});res.end(body);});
});
function send(c,what){if(!c||c.socket.destroyed)return;let s=Buffer.from(JSON.stringify(what));let header=s.length<126?Buffer.from([129,s.length]):s.length<=65535?Buffer.from([129,126,s.length>>8,s.length&255]):null;if(!header)return;c.socket.write(Buffer.concat([header,s]));}
function broadcast(r,obj){for(const p of r.players)send(p.client,obj);}
function publicRoom(r){return {type:'state',room:r.code,status:r.status,time:Math.max(0,Math.ceil(r.time)),map:r.map.cells,items:r.map.items.map(i=>({...i,taken:r.taken.has(i.id),active:r.active.has(i.id)})),exit:r.map.exit,players:r.players.map(p=>({id:p.id,name:p.name,x:p.x,y:p.y,angle:p.angle,down:p.down,dead:p.dead,reviveProgress:p.reviveTarget?Math.min(1,(Date.now()-p.reviveStart)/3000):0})),monster:{x:r.monster.x,y:r.monster.y},sigils:r.taken.size,generators:r.active.size,gate:r.gate,message:r.message,ready:r.players.length===2};}
function createRoom(){let code;do{code=crypto.randomBytes(3).toString('hex').toUpperCase();}while(rooms.has(code));const map=generate(crypto.randomBytes(4).readUInt32LE());const room={code,map,players:[],status:'waiting',time:20*60,taken:new Set(),active:new Map(),gate:false,monster:{x:map.monster.x,y:map.monster.y},monsterTarget:null,attackAt:0,bfsAt:0,monsterPath:[],message:'استعدا... شيء ما يتحرّك خلف الجدران.',lastTime:Date.now()};rooms.set(code,room);return room;}
function addPlayer(c,room,name){if(room.players.length>=2||room.status!=='waiting')return send(c,{type:'error',message:'الغرفة ممتلئة أو بدأت اللعبة.'});const s=room.map.spawn[room.players.length],p={client:c,id:crypto.randomBytes(4).toString('hex'),name:String(name||'ناجٍ').slice(0,18),x:s.x,y:s.y,angle:0,down:false,dead:false,downAt:0,reviveTarget:null,reviveStart:0,input:{x:0,y:0,run:false}};c.room=room;c.player=p;room.players.push(p);send(c,{type:'joined',id:p.id,room:room.code,index:room.players.length-1});if(room.players.length===2){room.status='playing';room.message='وجدتما بعضكما! اجمعا الأختام وشغّلا المولّدين قبل انتهاء الوقت.';room.lastTime=Date.now();broadcast(room,{type:'notice',message:'بدأت المطاردة! 20 دقيقة للهروب.'});}broadcast(room,publicRoom(room));}
function onMessage(c,data){let m;try{m=JSON.parse(data);}catch{return;}if(!m||typeof m!=='object')return;
  if(m.type==='create'&&!c.room){return addPlayer(c,createRoom(),m.name);}
  if(m.type==='join'&&!c.room){let room=rooms.get(String(m.code||'').trim().toUpperCase());if(!room)return send(c,{type:'error',message:'رمز الغرفة غير صحيح.'});return addPlayer(c,room,m.name);}
  const r=c.room,p=c.player;if(!r||!p)return;
  if(m.type==='chat'){let msg=String(m.text||'').replace(/[\x00-\x1f]/g,'').trim().slice(0,130);if(!msg)return;if(Date.now()-(c.lastChat||0)<650)return;c.lastChat=Date.now();return broadcast(r,{type:'chat',name:p.name,from:p.id,text:msg,at:Date.now()});}
  if(r.status!=='playing')return;
  if(m.type==='move'){let x=Number(m.x),y=Number(m.y);if(!Number.isFinite(x)||!Number.isFinite(y))return;let mag=Math.hypot(x,y);p.input={x:mag?Math.max(-1,Math.min(1,x/mag)):0,y:mag?Math.max(-1,Math.min(1,y/mag)):0,run:!!m.run};p.angle=Number.isFinite(m.angle)?m.angle%(2*Math.PI):0;}
  if(m.type==='revive-stop'){p.reviveTarget=null;}
  if(m.type==='answer'){const i=r.map.items.find(i=>i.id===String(m.id)&&i.type==='sigil');if(!i||r.taken.has(i.id)||p.down||p.dead||Math.hypot(i.x-p.x,i.y-p.y)>1.65)return;const puzzle=riddles[i.id];if(Number.isInteger(m.choice)&&m.choice===puzzle.answer){r.taken.add(i.id);broadcast(r,{type:'puzzle-result',id:i.id,correct:true});r.message='تم حل لغز '+i.title+'!';broadcast(r,{type:'notice',message:r.message});}else{send(c,{type:'puzzle-result',id:i.id,correct:false});send(c,{type:'notice',message:'إجابة خاطئة... لقد سمِعَك الوحش! حاول مجددًا.'});r.monsterTarget={id:p.id,until:Date.now()+10000};}if(r.taken.size===3&&r.active.size===2){r.gate=true;broadcast(r,{type:'notice',message:'انفتحت البوابة! اذهبا إليها معًا.'});}return;}
  if(m.type==='interact'){
    if(p.down||p.dead)return;
    const buddy=r.players.find(q=>q!==p&&q.down&&!q.dead&&Math.hypot(q.x-p.x,q.y-p.y)<1.75);
    if(buddy){p.reviveTarget=buddy.id;p.reviveStart=Date.now();return broadcast(r,{type:'notice',message:p.name+' يحاول إنعاش '+buddy.name+'...'});}
    const i=r.map.items.filter(i=>!r.taken.has(i.id)&&!r.active.has(i.id)).find(i=>Math.hypot(i.x-p.x,i.y-p.y)<1.5);
    if(i){if(i.type==='sigil'){send(c,{type:'puzzle',id:i.id,title:i.title,question:riddles[i.id].question,choices:riddles[i.id].choices});return;}else{r.active.set(i.id,Date.now());r.message='تم تشغيل '+i.title+'! يجب تشغيل المولّد الآخر خلال 30 ثانية.';}broadcast(r,{type:'notice',message:r.message});if(r.taken.size===3&&r.active.size===2){r.gate=true;r.message='البوابة فُتحت! اذهبا إلى نقطة الخروج معًا.';broadcast(r,{type:'notice',message:r.message});}return;}
    if(Math.hypot(p.x-r.map.exit.x,p.y-r.map.exit.y)<1.5&&!r.gate){return send(c,{type:'notice',message:'البوابة مغلقة. تحتاج إلى 3 أختام ومولّدَي الطاقة.'});}
  }
}
function dropClient(c){clients.delete(c);if(!c.room)return;const r=c.room;r.players=r.players.filter(p=>p.client!==c);if(r.players.length===0)rooms.delete(r.code);else{r.status='abandoned';r.endedAt=Date.now();broadcast(r,{type:'notice',message:'خرج شريكك من الغرفة. انتهت الجولة.'});broadcast(r,publicRoom(r));}c.room=null;}
server.on('upgrade',(req,socket)=>{if(req.url!=='/ws')return socket.destroy();const key=req.headers['sec-websocket-key'];if(typeof key!=='string')return socket.destroy();const accept=crypto.createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+accept+'\r\n\r\n');const c={socket,buffer:Buffer.alloc(0),room:null};clients.add(c);socket.on('data',chunk=>{c.buffer=Buffer.concat([c.buffer,chunk]);if(c.buffer.length>128*1024){socket.destroy();return;}while(c.buffer.length>=2){let a=c.buffer[0],b=c.buffer[1],masked=!!(b&128),len=b&127,off=2;if(!masked){socket.destroy();return;}if(len===126){if(c.buffer.length<4)break;len=c.buffer.readUInt16BE(2);off=4;}else if(len===127){if(c.buffer.length<10)break;const n=c.buffer.readBigUInt64BE(2);if(n>BigInt(8192)){socket.destroy();return;}len=Number(n);off=10;}if(len>8192){socket.destroy();return;}if(c.buffer.length<off+4+len)break;const mask=c.buffer.subarray(off,off+4),payload=Buffer.from(c.buffer.subarray(off+4,off+4+len));for(let i=0;i<len;i++)payload[i]^=mask[i%4];c.buffer=c.buffer.subarray(off+4+len);if((a&15)===8){socket.end();break;}if((a&15)===1)onMessage(c,payload.toString('utf8'));}});socket.on('close',()=>dropClient(c));socket.on('error',()=>dropClient(c));});
const dirs=[[1,0],[-1,0],[0,1],[0,-1]];
function gridPath(cells,from,to){let sx=Math.floor(from.x),sy=Math.floor(from.y),tx=Math.floor(to.x),ty=Math.floor(to.y),n=cells.length,key=(x,y)=>y*n+x,seen=new Set([key(sx,sy)]),parent=new Map(),q=[[sx,sy]];for(let h=0;h<q.length;h++){let [x,y]=q[h];if(x===tx&&y===ty)break;for(const [dx,dy] of dirs){let ax=x+dx,ay=y+dy,k=key(ax,ay);if(cells[ay]?.[ax]===0&&!seen.has(k)){seen.add(k);parent.set(k,[x,y]);q.push([ax,ay]);}}}let curr=key(tx,ty),first=null;if(!parent.has(curr))return null;while(parent.has(curr)){first=curr;const [px,py]=parent.get(curr);if(px===sx&&py===sy)break;curr=key(px,py);}return first==null?null:{x:(first%n)+.5,y:Math.floor(first/n)+.5};}
function step(r,dt){if(r.status!=='playing')return;r.time-=dt;if(r.time<=0){r.time=0;r.status='lost';r.endedAt=Date.now();r.message='انتهى الوقت... ابتلع الظلام آخر أمل.';broadcast(r,{type:'end',win:false,message:r.message});return;}
  const now=Date.now(),cells=r.map.cells;
  for(const p of r.players){if(p.dead)continue;if(p.down){if(now-p.downAt>75e3){p.dead=true;r.message=p.name+' ضاع في الظلام.';broadcast(r,{type:'notice',message:r.message});}continue;}let speed=p.input.run?3:2.05,dx=p.input.x*speed*dt,dy=p.input.y*speed*dt;if(!wall(cells,p.x+dx,p.y))p.x+=dx;if(!wall(cells,p.x,p.y+dy))p.y+=dy;
    if(p.reviveTarget){const b=r.players.find(q=>q.id===p.reviveTarget);if(!b||!b.down||b.dead||Math.hypot(b.x-p.x,b.y-p.y)>1.75){p.reviveTarget=null;}else if(now-p.reviveStart>=3000){b.down=false;b.downAt=0;p.reviveTarget=null;r.message=p.name+' أنعش '+b.name+'!';broadcast(r,{type:'notice',message:r.message});}}
  }
  if(r.active.size===1){for(const [id,at] of r.active){if(now-at>30e3){r.active.clear();broadcast(r,{type:'notice',message:'انطفأ المولّد! يجب تشغيل الاثنين بفارق أقل من 30 ثانية.'});break;}}}
  if(r.players.every(p=>p.down||p.dead)){r.status='lost';r.endedAt=Date.now();r.message='سقط الناجيان... لا أحد يسمع الصراخ.';broadcast(r,{type:'end',win:false,message:r.message});return;}
  if(r.gate&&r.players.every(p=>!p.down&&!p.dead&&Math.hypot(p.x-r.map.exit.x,p.y-r.map.exit.y)<1.5)){r.status='won';r.endedAt=Date.now();r.message='نجوتما من الممر الأخير!';broadcast(r,{type:'end',win:true,message:r.message});return;}
  const closest=r.players.filter(p=>!p.down&&!p.dead).sort((a,b)=>Math.hypot(a.x-r.monster.x,a.y-r.monster.y)-Math.hypot(b.x-r.monster.x,b.y-r.monster.y))[0];const angry=r.monsterTarget&&r.monsterTarget.until>Date.now()?r.players.find(p=>p.id===r.monsterTarget.id&&!p.down&&!p.dead):null;const prey=angry||closest;
  if(prey){if(now-r.bfsAt>650){r.monsterPath=gridPath(cells,r.monster,prey)||[];r.bfsAt=now;}const target=(r.monsterPath&&Number.isFinite(r.monsterPath.x))?r.monsterPath:{x:prey.x,y:prey.y};let vx=target.x-r.monster.x,vy=target.y-r.monster.y,dist=Math.hypot(vx,vy);if(dist>.07){const step=Math.min(dist,1.54*dt);const nx=r.monster.x+vx/dist*step,ny=r.monster.y+vy/dist*step;if(!wall(cells,nx,ny,.13)){r.monster.x=nx;r.monster.y=ny;}}
    for(const p of r.players){if(!p.down&&!p.dead&&Math.hypot(p.x-r.monster.x,p.y-r.monster.y)<.78&&now-r.attackAt>1900){p.down=true;p.downAt=now;r.attackAt=now;broadcast(r,{type:'notice',message:'الوحش أمسك '+p.name+'! أسرع لإنعاشه!'});}}
  }
}
setInterval(()=>{const now=Date.now();for(const r of rooms.values()){const dt=Math.max(0,Math.min(.12,(now-r.lastTime)/1000));r.lastTime=now;step(r,dt);} },50);
setInterval(()=>{for(const r of rooms.values())if(r.status!=='abandoned'&&r.players.length)broadcast(r,publicRoom(r));},150);
setInterval(()=>{for(const [code,r] of rooms)if(r.players.length===0||((r.status==='won'||r.status==='lost'||r.status==='abandoned')&&Date.now()-(r.endedAt||r.lastTime)>180000))rooms.delete(code);},60000);
if(require.main===module)server.listen(PORT,'0.0.0.0',()=>console.log('THE LAST CORRIDOR online on http://localhost:'+PORT));
module.exports={rooms,createRoom,addPlayer,onMessage,step,gridPath,publicRoom,dropClient,server,riddles};


